### ISSUE TITLE
ngsLCA_profile fails to split taxa names

### ISSUE THREAD

**Issue by slennart** [wyc661217/ngsLCA#1]
I have generated a bunch of lca files which I would now like to read and process using the ngsLCA R package. However, in the first step where I create a ngsLCA profile, I get the following error: `Error in x[2:(length(x) - 1)] : only 0's may be mixed with negative subscripts`

I did a bit of digging and found that this is related to the taxa names being split. When I check the intermediate files, taxa_profile_final.txt gets created, but the taxonomic_profile folder remains empty so the last step of ngsLCA_profile seems to fail. 

I have attached the taxa_profile_final.txt that seems to cause the issue:
[taxa_profile_final.txt](https://github.com/wyc661217/ngsLCA/files/13295461/taxa_profile_final.txt)

**Comment by wyc661217** [comment]
Hi sorry for a late response. Can you share the input lca file for this?

**Comment by slennart** [comment]
Of course, attached is an example lca file.
[cap01_Lib006_002.zip](https://github.com/wyc661217/ngsLCA/files/13473981/cap01_Lib006_002.zip)

**Comment by wyc661217** [comment]
Updated the ngsLCA_profile function in this repository. If you install the new version the problem should be fixed.

**Comment by slennart** [comment]
Thanks! I updated the version and ran ngsLCA_profile again. I am not getting the previous error message anymore and I do get a "complete_profile.txt" file. However, I still get the following error message:                                                                      
1: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on '$path/cap01_Lib006_002.lca'

**Comment by wyc661217** [comment]
I think this is because your input lca file was trimmed so the last line of it does not end with a "End Of Line character" (normally \n). It will not cause problem. If you input a full lca file it should not give this Warning message.

**Comment by slennart** [comment]
Okay, I see. Thanks a lot again for resolving the issue.
